apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gjq7ftf7u-java-springboot 
  janus-idp.io/tekton: gjq7ftf7u-java-springboot
  backstage.io/kubernetes-id: gjq7ftf7u-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjq7ftf7u-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  